Transferred from the Adobe Open Source Subversion Repository
Revision: 4545
Author:   dloverin@adobe.com
Date:     2009-01-15T22:47:08.091587Z

Log Message: 
-----------
Fix RTE in FxComponent caused by processing events for an unloaded application.
There are many stack traces in SDK-17703. The following is the one that is fixed by this change:
TypeError: Error #1009: Cannot access a property or method of a null object reference. 
    at mx.components.baseClasses::FxComponent/getSkinPartMetadata() 
    at mx.components.baseClasses::FxComponent/findSkinParts() 
    at mx.components.baseClasses::FxComponent/loadSkin() 
    at mx.components.baseClasses::FxComponent/commitProperties() 
    

QE Notes: None
Doc Notes: None
Bugs: SDK-17703
Reviewer: Ryan
tests: checkintests

Modified Paths:
--------------
/flex/sdk/trunk/frameworks/projects/flex4/src/mx/components/baseClasses/FxComponent.as

git-svn-id: https://svn.apache.org/repos/asf/incubator/flex/trunk/frameworks@1282690 13f79535-47bb-0310-9956-ffa450edef68